create table BRAND (
    ID varchar(36) not null,
    NAME varchar(200)
);

ALTER TABLE BRAND ADD CONSTRAINT PK_BRAND PRIMARY KEY (ID);

-- product fk.
ALTER TABLE PRODUCT ADD BRAND_ID varchar(36);
ALTER TABLE PRODUCT ADD CONSTRAINT FK_PRODUCT_0 FOREIGN KEY (BRAND_ID) REFERENCES BRAND (ID);
