create table CATEGORY (
    ID varchar(36) not null,
    NAME varchar(200)
);

ALTER TABLE CATEGORY ADD CONSTRAINT PK_CATEGORY PRIMARY KEY (ID);


create table PRODUCT_CATEGORY_MAP (
    ID varchar(36) not null,
    CATEGORY_ID varchar(36),
    PRODUCT_ID varchar(36)
);

ALTER TABLE PRODUCT_CATEGORY_MAP ADD CONSTRAINT PK_PRODUCT_CATEGORY_MAP PRIMARY KEY (ID);


ALTER TABLE PRODUCT_CATEGORY_MAP ADD CONSTRAINT FK_PRODUCT_CATEGORY_MAP_0 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID);
ALTER TABLE PRODUCT_CATEGORY_MAP ADD CONSTRAINT FK_PRODUCT_CATEGORY_MAP_1 FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID);
