create table TAG (
    ID varchar(36) not null,
    TYPE varchar(20),
    NAME varchar(200)
);

ALTER TABLE TAG ADD CONSTRAINT PK_TAG PRIMARY KEY (ID);

create table PRODUCT_TAG_MAP (
    ID varchar(36) not null,
    TAG_ID varchar(36),
    PRODUCT_ID varchar(36),
    VALUE varchar(200)
);

ALTER TABLE PRODUCT_TAG_MAP ADD CONSTRAINT PK_PRODUCT_TAG_MAP PRIMARY KEY (ID);

ALTER TABLE PRODUCT_TAG_MAP ADD CONSTRAINT FK_PRODUCT_TAG_MAP_0 FOREIGN KEY (PRODUCT_ID ) REFERENCES PRODUCT (ID);
ALTER TABLE PRODUCT_TAG_MAP ADD CONSTRAINT FK_PRODUCT_TAG_MAP_1 FOREIGN KEY (TAG_ID     ) REFERENCES TAG     (ID);
