apiVersion: v1
kind: Service
metadata:
  name: maxec-web-frontend
  labels:
    app: maxec-web-frontend
spec:
  type: NodePort
  ports:
  - port: 11000
    name: ap
    targetPort: 11000
    protocol: TCP
  selector:
    app: maxec-web-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxec-web-frontend-deployment
  labels:
    app: maxec-web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maxec-web-frontend
  template:
    metadata:
      labels:
        app: maxec-web-frontend
    spec:
      containers:
      - name: maxec-web-frontend
        image: host.docker.internal:5000/maxec-web-frontend:BRANCH-VERSION # will be replaced by jenkins
        env:
        - name: API_PRODUCT_ENDPOINT     
          value: maxec-biz-product:13000
        - name: API_SEARCH_ENDPOINT     
          value: maxec-biz-search:13200
        - name: API_SHOPPING_ENDPOINT     
          value: maxec-biz-shopping:13300
        - name: API_CONTENT_ENDPOINT     
          value: maxec-biz-content:13400
        - name: API_CUSTOMER_ENDPOINT     
          value: maxec-biz-customer:13500
        - name: DBDRV     
          value: org.postgresql.Driver
        - name: DBUSER
          value: maxec
        - name: DBPASS
          value: maxec
        - name: DBDIALECT 
          value: org.hibernate.dialect.PostgreSQL9Dialect
        ports:
        - containerPort: 11000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: digimon-ingress
spec:
  rules:
    - host: frontend.
      http:
        paths:
          - path: /
            frontend:
              serviceName: maxec-web-frontend
              servicePort: 11000
  
