apiVersion: v1
kind: Service
metadata:
  name: maxec-web-backend
  labels:
    app: maxec-web-backend
spec:
  type: NodePort
  ports:
  - port: 11100
    name: ap
    targetPort: 11100
    protocol: TCP
  selector:
    app: maxec-web-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxec-web-backend-deployment
  labels:
    app: maxec-web-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maxec-web-backend
  template:
    metadata:
      labels:
        app: maxec-web-backend
    spec:
      containers:
      - name: maxec-web-backend
        image: host.docker.internal:5000/maxec-web-backend:BRANCH-VERSION # will be replaced by jenkins
        ports:
        - containerPort: 11100

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: digimon-ingress
spec:
  rules:
    - host: backend.
      http:
        paths:
          - path: /
            backend:
              serviceName: maxec-web-backend
              servicePort: 11100
  
