apiVersion: v1
kind: Service
metadata:
  name: maxec-biz-content
  labels:
    app: maxec-biz-content
spec:
  type: NodePort
  ports:
  - port: 13400
    name: ap
    targetPort: 13400
    protocol: TCP
  - port: 80
    name: web
    targetPort: 80
    protocol: TCP
  selector:
    app: maxec-biz-content
