apiVersion: v1
kind: Service
metadata:
  name: maxec-app-frontend
  labels:
    app: maxec-app-frontend
spec:
  type: NodePort
  ports:
  - port: 12000
    name: ap
    protocol: TCP
    targetPort: 12000
  selector:
    app: maxec-app-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maxec-app-frontend-deployment
  labels:
    app: maxec-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maxec-app-frontend
  template:
    metadata:
      labels:
        app: maxec-app-frontend
    spec:
      containers:
      - name: maxec-app-frontend
        image: host.docker.internal:5000/maxec-app-frontend:BRANCH-VERSION # will be replaced by jenkins
        env:
        - name: DBURL     
          value: jdbc:postgresql://maxec-db/maxec
        - name: DBDRV     
          value: org.postgresql.Driver
        - name: DBUSER
          value: maxec
        - name: DBPASS
          value: maxec
        - name: DBDIALECT 
          value: org.hibernate.dialect.PostgreSQL9Dialect
        ports:
        - containerPort: 12000
  
