app:
   es:
      hosts: localhost:9200

logging:
   level:
      root: INFO
      org:
         springframework:
            data:
               elasticsearch:
                  core: DEBUG
         elasticsearch:
            client: DEBUG