---
- hosts: kubernetes
  become: true
  tasks:
  - copy: src=yum_repository/kubernetes.repo dest=/etc/yum.repos.d owner=root mode='0644'

  - selinux: policy=targeted state=permissive

  - yum: name=kubelet,kubeadm,kubectl state=present disable_excludes=kubernetes
  
  # disable swap
  - command: swapoff -a


  - copy: src=config_repository/k8s_modules.conf dest=/etc/modules-load.d/k8s.conf owner=root mode=0644

  # run 'ansible-galaxy collection install community.general'
 
  - community.general.modprobe: name=br_netfilter state=present

  - sysctl: sysctl_file=/etc/sysctl.d/k8s.conf name=net.bridge.bridge-nf-call-ip6tables value='1' reload=yes
  - sysctl: sysctl_file=/etc/sysctl.d/k8s.conf name=net.bridge.bridge-nf-call-iptables  value='1' reload=yes

  - service: name=kubelet enabled=yes

  # run:
  #   # kubeadm init --pod-network-cidr=10.244.0.0/16
  #   # kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  #
  #   > mkdir -p $HOME/.kube/config/
  #   > sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config/
  #   > sudo chown $(id -u):$(id -g) $HOME/.kube/config/admin.conf

  # service -----------------------------
  - service: name=kubelet state=started
    tags: [never,start]

